name: Mini Projet
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Build
        run: docker compose -f docker-compose.yml -p mini-projet-mlops build
      - name: Docker Tag
        run: docker tag mini-projet-mlops elianajunker/mini-projet-mlops:latest
      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Docker push
        run: docker push elianajunker/mini-projet-mlops
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker pull elianajunker/mini-projet-mlops && \
            docker restart fastapi-house-price-app
