name: Mini Projet
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Build
        run: docker compose -f docker-compose.yml -p mini-projet-mlops build
      - name: Docker Tag
        run: docker tag mini-projet-mlops ${{ secrets.DOCKER_USERNAME }}/mini-projet-mlops:latest
      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Docker push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mini-projet-mlops
      - name: Deploy to Server
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no "${{ secrets.SSH_HOST }}" << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/mini-projet-mlops
            docker kill mini-projet-mlops; docker rm mini-projet-mlops; docker run -d --name mini-projet-mlops -p 8005:8005 ${{ secrets.DOCKER_USERNAME }}/mini-projet-mlops
          EOF
            
